
export enum  productEnum {
    PRODUCT_CREATED = 'CREATE_PRODUCT',
    PRODUCT_UPDATED = 'UPDATE_PRODUCT',
    PRODUCT_DELETED = 'DELETE_PRODUCT',
    GET_PRODUCTS = 'GET_PRODUCTS',
    GET_PRODUCT = 'GET_PRODUCT'
    
}